apiVersion: v2
name: ztwim
description: Zero Trust Workload Identity Manager Helm Chart
type: application
version: 0.1.2
home: https://github.com/validatedpatterns/ztwim-chart
maintainers:
  - name: Validated Patterns Team
    email: validatedpatterns@googlegroups.com
